services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip_all &
        sleep 5 &&
        mongosh --eval 'rs.initiate({
          _id:\"rs0\",
          members:[{ _id:0, host:\"mongodb:27017\" }]
        })' &&
        wait
      "

  backend_mongoose:
    build:
      context: ./backend_mongoose
      dockerfile: Dockerfile
    container_name: backend_mongoose
    ports:
      - "3001:3001"
    env_file:
      - ./backend_mongoose/.env
    environment:
      MONGO_URI: "mongodb://mongodb:27017/ticketway?replicaSet=rs0"
    depends_on:
      - mongodb

  dashboard_admin:
    build:
      context: ./dashboard_admin
      dockerfile: Dockerfile
    container_name: dashboard_admin
    ports:
      - "3003:3003"
    env_file:
      - ./dashboard_admin/.env
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/ticketway?replicaSet=rs0"
    depends_on:
      - mongodb

  user_company_ms:
    build: ./dashboard_company
    container_name: user_company_ms
    command: node dist/src/user-company-ms/main.js
    env_file:
      - ./dashboard_company/.env
    depends_on:
      - mongodb

  product_ms:
    build: ./dashboard_company
    container_name: product_ms
    command: node dist/src/product-ms/main.js
    env_file:
      - ./dashboard_company/.env
    depends_on:
      - mongodb

  product_category_ms:
    build: ./dashboard_company
    container_name: product_category_ms
    command: node dist/src/product-category-ms/main.js
    env_file:
      - ./dashboard_company/.env
    depends_on:
      - mongodb

  dashboard_company_gateway:
    build: ./dashboard_company
    container_name: dashboard_company_gateway
    command: node dist/src/main.js
    ports:
      - "3002:3002"
    env_file:
      - ./dashboard_company/.env
    depends_on:
      - user_company_ms
      - product_ms
      - product_category_ms

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend_mongoose
      - dashboard_admin
      - dashboard_company_gateway

volumes:
  mongo_data:
