FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY app ./app
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3001
CMD ["node", "app/api/index.js"]
